### ISSUE TITLE
update sim to map space/enter to A/B

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-arcadeshield#55]
like in Arcade...

**Comment by eanders-ms** [comment]
A few things to consider before going this direction:

* The controls won't be intuitive or guessable. We may need to add in-simulator guidance (like Arcade's keyboard shortcuts popup, see below).
* It would prevent accessible button access. Tabbing to a button and pressing space will always click the A button instead of the currently selected button. Arcade's simulator controls are not tabbable because of this.

![image](https://github.com/user-attachments/assets/e5a2b4fe-98e4-4256-b48d-1ede1edaa5d5)

**Comment by tballmsft** [comment]
good point - accessibility is a key feature for micro:bit.

**Comment by tballmsft** [comment]
let's keep as is.
